### ISSUE TITLE
Service 'tor_countries' timed out.

### ISSUE THREAD

**Issue by mane** [mweinelt/munin-tor#16]
Hi there,

I'm experiencing an issue with this plugin.

From munin-node.log I see the following messages:

2016/01/04-16:40:08 [13960] Error output from tor_connections:
2016/01/04-16:40:08 [13960]     No response from Tor daemon in TorConnection.fetch()
2016/01/04-16:40:08 [13960] Service 'tor_connections' exited with status 255/0.
2016/01/04-16:40:45 [13959] Error output from tor_countries:
2016/01/04-16:40:45 [13959]     Traceback (most recent call last):
2016/01/04-16:40:45 [13959]       File "/etc/munin/plugins/tor_countries", line 337, in <module>
2016/01/04-16:40:45 [13959]         main()
2016/01/04-16:40:45 [13959]       File "/etc/munin/plugins/tor_countries", line 332, in main
2016/01/04-16:40:45 [13959]         provider.fetch()
2016/01/04-16:40:45 [13959]       File "/usr/share/munin-tor/circuits_by_country.py", line 80, in fetch
2016/01/04-16:40:45 [13959]         countries_num = self.top_countries()
2016/01/04-16:40:45 [13959]       File "/usr/share/munin-tor/circuits_by_country.py", line 123, in top_countries
2016/01/04-16:40:45 [13959]         c = Counter(self._gen_countries(controller))
2016/01/04-16:40:45 [13959]       File "/usr/lib/python2.7/collections.py", line 449, in __init__
2016/01/04-16:40:45 [13959]         self.update(iterable, **kwds)
2016/01/04-16:40:45 [13959]       File "/usr/lib/python2.7/collections.py", line 530, in update
2016/01/04-16:40:45 [13959]         for elem in iterable:
2016/01/04-16:40:45 [13959]       File "/usr/share/munin-tor/circuits_by_country.py", line 110, in _gen_countries
2016/01/04-16:40:45 [13959]         for ipaddr in self._gen_ipaddrs_from_statuses(controller):
2016/01/04-16:40:45 [13959]       File "/usr/share/munin-tor/circuits_by_country.py", line 104, in _gen_ipaddrs_from_statuses
2016/01/04-16:40:45 [13959]         for desc in controller.get_network_statuses():
2016/01/04-16:40:45 [13959]       File "/usr/local/lib/python2.7/dist-packages/stem/control.py", line 427, in wrapped
2016/01/04-16:40:45 [13959]         raise exc
2016/01/04-16:40:45 [13959]     stem.SocketClosed
2016/01/04-16:40:45 [13959] Service 'tor_countries' exited with status 1/0.
2016/01/04-16:41:02 [13960] Service 'interrupts' timed out.
2016/01/04-16:41:04 [13960] Service 'interrupts' timed out.
2016/01/04-16:50:08 [15212] Error output from tor_connections:
2016/01/04-16:50:08 [15212] No response from Tor daemon in TorConnection.fetch()
2016/01/04-16:50:08 [15212] Service 'tor_connections' exited with status 255/0.

Any idea what could be wrong on my config?

Thank you and keep the good work up!

--
mane

**Comment by mane** [comment]
*** UPDATE ***

I also see these:

2016/01/04-16:50:08 [15212] Error output from tor_connections:
2016/01/04-16:50:08 [15212]     No response from Tor daemon in TorConnection.fetch()
2016/01/04-16:50:08 [15212] Service 'tor_connections' exited with status 255/0.

**Comment by mweinelt** [comment]
The script is still working for me, something in the connection to the tor daemon seems to be not working for you.

Can you try setting up cookie auth as described in https://github.com/mweinelt/munin-tor/issues/11#issuecomment-68633802?

**Comment by mane** [comment]
Hi @mweinelt,

Thanks for your quick reply. I've tried as you suggested but with no success so far.

Here is what I get into the log:

2016/01/04-19:55:28 [1238] Error output from tor_dormant:
2016/01/04-19:55:28 [1238]      2016/01/04-19:55:28 [1416] User 'tor' required for 'tor_dormant' does not exist. at /usr/share/perl5/Munin/Node/OS.pm line 183

**Comment by mane** [comment]
I've checked my /etc/passwd and the user is not "tor" but "debian-tor" (as it is a raspbian OS).

Let's see if it likes that.

**Comment by mane** [comment]
2016/01/04-20:10:03 CONNECT TCP Peer: "[127.0.0.1]:40091" Local: "[127.0.0.1]:4949"
2016/01/04-20:11:00 [3272] Service 'tor_countries' timed out.
2016/01/04-20:11:02 [3272] Service 'tor_countries' timed out.
2016/01/04-20:11:03 [3272] Node side timeout while processing: 'config memory'

**Comment by mane** [comment]
Hope this can be useful to figure out what's wrong with my config as it seems to be all working except for the graphs:

pi@raspberrypi ~ $ sudo munin-run --debug tor_dormant 
# Processing plugin configuration from /etc/munin/plugin-conf.d/munin-node
# Processing plugin configuration from /etc/munin/plugin-conf.d/tor_
# Setting /rgid/ruid/ to /114/0/
# Setting /egid/euid/ to /114 114 0/0/
# Setting up environment
# About to run '/etc/munin/plugins/tor_dormant'
dormant.value 0
pi@raspberrypi ~ $ sudo munin-run --debug tor_traffic 
# Processing plugin configuration from /etc/munin/plugin-conf.d/munin-node
# Processing plugin configuration from /etc/munin/plugin-conf.d/tor_
# Setting /rgid/ruid/ to /114/0/
# Setting /egid/euid/ to /114 114 0/0/
# Setting up environment
# About to run '/etc/munin/plugins/tor_traffic'
read.value 493302702
written.value 492465149

**Comment by mane** [comment]
All working now.

Apparently it was just a matter of time.

For the record:

I've modified the content of /etc/munin/plugin-conf.d/munin-node and added:

[tor_*]
timeout 60
user debian-tor
group debian-tor

enabled cookie auth as described in #11 (comment)

Thank you.
